%% HRL file generated by ERLSOM
%%
%% It is possible (and in some cases necessary) to change the name of
%% the record fields.
%%
%% It is possible to add default values, but be aware that these will
%% only be used when *writing* an xml document.


-type anyAttrib()  :: {{string(),    %% name of the attribute
                        string()},   %% namespace
                       string()}.    %% value

-type anyAttribs() :: [anyAttrib()] | undefined.

%% xsd:QName values are translated to #qname{} records.
%-record(qname, {uri :: string(),
%                localPart :: string(),
%                prefix :: string(),
%                mappedPrefix :: string()}).



-record(payload, {anyAttribs :: anyAttribs(),
	payload :: string()}).

-type payload() :: #payload{}.


-record(wayref, {anyAttribs :: anyAttribs(),
	id :: string()}).

-type wayref() :: #wayref{}.


-record(noderef, {anyAttribs :: anyAttribs(),
	id :: string()}).

-type noderef() :: #noderef{}.


-record(waynodes, {anyAttribs :: anyAttribs(),
	maximum :: string()}).

-type waynodes() :: #waynodes{}.


-record(tile_deg, {anyAttribs :: anyAttribs(),
	level :: string(),
	lat :: string(),
	lon :: string()}).

-type tile_deg() :: #tile_deg{}.


-record(tile_num, {anyAttribs :: anyAttribs(),
	level :: string(),
	x :: string(),
	y :: string()}).

-type tile_num() :: #tile_num{}.


-record(version, {anyAttribs :: anyAttribs(),
	minimum :: string(),
	maximum :: string()}).

-type version() :: #version{}.


-record(traffic_api, {anyAttribs :: anyAttribs(),
	version :: version(),
	choice :: tile_num() | tile_deg(),
	waynodes :: waynodes(),
	'traffic_api/SEQ1' :: 'traffic_api/SEQ1'() | undefined,
	payload :: string()}).

-type traffic_api() :: #traffic_api{}.


-record('traffic_api/SEQ1', {anyAttribs :: anyAttribs(),
	wayref :: wayref(),
	noderef :: noderef() | undefined}).

-type 'traffic_api/SEQ1'() :: #'traffic_api/SEQ1'{}.


-record(osm_traffic, {anyAttribs :: anyAttribs(),
	version :: string() | undefined,
	generator :: string() | undefined,
	traffic_api :: traffic_api()}).

-type osm_traffic() :: #osm_traffic{}.